import { NextRequest, NextResponse } from "next/server";
import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";
import { generatePRComment } from "@/app/utils/prCommentFormatter";
import { analyzePullRequest } from "@/app/services/prAnalyzer";
import {
  createRepoUsageKey,
  DEFAULT_LIMIT_REACHED_MESSAGE,
  FREE_LIMIT_COMMENT_BODY,
  incrementUsage,
  isDeveloperRepoOwner,
  isLimitReached,
} from "@/app/lib/usageTracker";

const MERGEMIND_COMMENT_MARKERS = [
  "MergeMind Analysis",
  "Generated by MergeMind",
  "MergeMind free limit reached",
];

async function upsertMergeMindComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  issueNumber: number,
  body: string,
) {
  const comments = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: issueNumber,
  });

  const existingComment = comments.data.find((comment) =>
    MERGEMIND_COMMENT_MARKERS.some((marker) => comment.body?.includes(marker)),
  );

  if (existingComment?.id) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingComment.id,
      body,
    });
    return;
  }

  await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body,
  });
}

export async function POST(req: NextRequest) {
  try {
    const payload = await req.json();
    const event = req.headers.get("x-github-event");

    if (event === "pull_request") {
      const action = payload.action;

      if (action === "opened" || action === "synchronize") {
        const pr = payload.pull_request;

        const prUrl = pr.html_url;
        const repo = payload.repository.name;
        const owner = payload.repository.owner.login;
        const prNumber = pr.number;
        const installationId = payload.installation.id;
        const isDevOwner = isDeveloperRepoOwner(owner);
        const repoKey = createRepoUsageKey(owner, repo);

        console.log("Processing PR:", prUrl);

        const octokit = new Octokit({
          authStrategy: createAppAuth,
          auth: {
            appId: process.env.GITHUB_APP_ID!,
            privateKey: process.env.GITHUB_PRIVATE_KEY!,
            installationId: installationId,
          },
        });

        if (!isDevOwner && isLimitReached(repoKey)) {
          console.log("Limit reached for repo:", repoKey);

          await upsertMergeMindComment(
            octokit,
            owner,
            repo,
            prNumber,
            FREE_LIMIT_COMMENT_BODY,
          );

          return NextResponse.json({
            skipped: true,
            reason: DEFAULT_LIMIT_REACHED_MESSAGE,
          });
        }

        if (!isDevOwner) {
          incrementUsage(repoKey);
        }

        const data = await analyzePullRequest(prUrl);

        if (
          !data.analysis ||
          !data.mergeReadiness ||
          !data.blastRadius ||
          !data.compliance
        ) {
          throw new Error("Incomplete PR analysis response");
        }

        const commentBody = generatePRComment({
          analysis: data.analysis,
          mergeReadiness: data.mergeReadiness,
          blastRadius: data.blastRadius,
          compliance: data.compliance,
          repository: {
            ...data.repository,
            changedFiles: data.repository?.changedFiles || [],
            totalFiles: data.repository?.totalFiles || 0,
            prUrl,
          },
          appUrl: process.env.APP_URL,
        });

        await upsertMergeMindComment(octokit, owner, repo, prNumber, commentBody);
        console.log("Updated MergeMind PR comment");
      }
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Webhook error:", error);
    return NextResponse.json({ error: "Webhook failed" }, { status: 500 });
  }
}
