/**
 * Formats PR analysis data into a GitHub PR comment
 * Generates structured, developer-friendly comments with clear formatting
 */

import { 
  PRAnalysisWithRiskScore, 
  BlastRadius, 
  ComplianceResult, 
  MergeReadiness 
} from "@/app/types/prAnalysis";

export interface PRCommentData {
  analysis: PRAnalysisWithRiskScore;
  mergeReadiness: MergeReadiness;
  blastRadius: BlastRadius;
  compliance: ComplianceResult;
  repository?: {
    changedFiles: string[];
    totalFiles: number;
  };
  appUrl?: string;
}

/**
 * Generate a GitHub-ready PR comment from analysis data
 */
export function generatePRComment(data: PRCommentData): string {
  const {
    analysis,
    mergeReadiness,
    blastRadius,
    compliance,
    repository,
    appUrl,
  } = data;

  const statusEmoji = getStatusEmoji(mergeReadiness.status);
  const statusColor = getStatusColor(mergeReadiness.status);
  const complianceLevel = getComplianceLevel(compliance.riskLevel);
  const confidencePercent = Math.round(analysis.confidenceScore * 100);

  // Calculate critical files (core changes only)
  const criticalFiles = blastRadius.layerDetails
    ? Object.entries(blastRadius.layerDetails)
        .flatMap(([layer, details]) =>
          details.files
            .filter((f) => f.isCritical)
            .map((f) => ({
              path: f.path,
              reason: f.reason,
              layer,
            }))
        )
        .slice(0, 5) // Top 5 critical files
    : [];

  // Format the comment
  const comment = `---

${statusEmoji} **MergeMind Analysis**

## ${statusColor}
**Recommendation:** ${getRecommendation(mergeReadiness.status)}

**Why this matters:**
${formatWhyItMatters(mergeReadiness.status, analysis.issues.length)}

---

## 📊 Key Metrics

| Metric            | Value        | Meaning |
|------------------|-------------|--------|
| Risk Level       | ${analysis.riskLevel}        | ${getRiskMeaning(analysis.riskLevel)} |
| Impact Score     | ${mergeReadiness.score} / 100    | ${getImpactMeaning(mergeReadiness.score)} |
| Compliance       | ${complianceLevel}         | ${getComplianceMeaning(compliance.riskLevel)} |
| Confidence       | ${confidencePercent}%         | Analysis reliability |

---

## 🔍 What changed

${formatWhatChanged(blastRadius, repository)}

---

${criticalFiles.length > 0 ? formatCriticalFilesSection(criticalFiles) : ""}

## ✅ Suggested Improvements

${formatSuggestions(analysis.improvements)}

---

## 🧠 Final Verdict

${statusEmoji} **${getFinalVerdictText(mergeReadiness.status)}**

👉 ${getFinalVerdictAction(mergeReadiness.status)}

---

## 📘 How to read this

- 🟢 SAFE → Good to merge
- 🟡 CAUTION → Review important areas
- 🔴 BLOCK → Fix before merging

---

${appUrl ? `🔗 View full detailed analysis: ${appUrl}\n\n` : ""}---

*Generated by MergeMind • PR Analysis Engine*`;

  return comment.trim();
}

function getStatusEmoji(status: string): string {
  switch (status) {
    case "SAFE":
      return "🟢";
    case "CAUTION":
      return "🟡";
    case "BLOCK":
      return "🔴";
    default:
      return "⚪";
  }
}

function getStatusColor(status: string): string {
  switch (status) {
    case "SAFE":
      return "🟢 SAFE";
    case "CAUTION":
      return "🟡 CAUTION";
    case "BLOCK":
      return "🔴 BLOCK";
    default:
      return "⚪ UNKNOWN";
  }
}

function getRecommendation(status: string): string {
  switch (status) {
    case "SAFE":
      return "Good to merge";
    case "CAUTION":
      return "Review before merging";
    case "BLOCK":
      return "Do not merge yet";
    default:
      return "Review required";
  }
}

function formatWhyItMatters(
  status: string,
  issueCount: number
): string {
  const lines: string[] = [];

  switch (status) {
    case "SAFE":
      lines.push("- Low risk detected in code changes");
      lines.push("- No major concerns identified");
      lines.push("- Safe to merge immediately");
      break;
    case "CAUTION":
      lines.push("- Moderate risk detected in code changes");
      lines.push("- Some important logic areas affected");
      lines.push("- Review recommended before merging");
      break;
    case "BLOCK":
      lines.push("- High risk detected in code changes");
      lines.push("- Critical issues must be addressed");
      lines.push("- Address concerns before merging");
      break;
  }

  if (issueCount > 0) {
    lines.push(`- ${issueCount} issue${issueCount !== 1 ? "s" : ""} found`);
  }

  return lines.map((l) => l).join("\n");
}

function getRiskMeaning(riskLevel: string): string {
  switch (riskLevel) {
    case "LOW":
      return "Minimal impact expected";
    case "MEDIUM":
      return "Moderate impact possible";
    case "HIGH":
      return "May introduce issues";
    default:
      return "Risk assessment pending";
  }
}

function getImpactMeaning(score: number): string {
  if (score < 40) return "Low system impact";
  if (score < 70) return "Moderate system impact";
  return "High system impact";
}

function getComplianceLevel(riskLevel: string): string {
  switch (riskLevel) {
    case "LOW":
      return "LOW";
    case "MEDIUM":
      return "MEDIUM";
    case "HIGH":
      return "HIGH";
    default:
      return "UNKNOWN";
  }
}

function getComplianceMeaning(riskLevel: string): string {
  switch (riskLevel) {
    case "LOW":
      return "No major security concerns";
    case "MEDIUM":
      return "Some security review needed";
    case "HIGH":
      return "Critical security concerns";
    default:
      return "Security review pending";
  }
}

function formatWhatChanged(
  blastRadius: BlastRadius,
  repository?: { changedFiles: string[]; totalFiles: number }
): string {
  const lines: string[] = [];

  if (blastRadius.affectedLayers.length > 0) {
    lines.push(
      `- ${blastRadius.affectedLayers.length} architectural layer${
        blastRadius.affectedLayers.length !== 1 ? "s" : ""
      } affected`
    );
    lines.push(`- Layers: ${blastRadius.affectedLayers.join(", ")}`);
  }

  if (repository) {
    lines.push(`- ${repository.changedFiles.length} file${repository.changedFiles.length !== 1 ? "s" : ""} changed`);
  }

  if (blastRadius.impactScore) {
    lines.push(`- Impact score: ${blastRadius.impactScore}%`);
  }

  return lines.length > 0
    ? lines.map((l) => l).join("\n")
    : "- Analysis data unavailable";
}

function formatCriticalFilesSection(
  criticalFiles: Array<{ path: string; reason: string; layer: string }>
): string {
  if (criticalFiles.length === 0) return "";

  const fileList = criticalFiles
    .map((f) => `- **${f.path}** → ${f.reason}`)
    .join("\n");

  return `## 🔥 Critical Files (High Attention)\n\n${fileList}\n\n`;
}

function formatSuggestions(improvements: string[]): string {
  if (improvements.length === 0) {
    return "- Code looks good\n- Keep maintaining the current standards";
  }

  return improvements.slice(0, 5)
    .map((s) => `- ${s}`)
    .join("\n");
}

function getFinalVerdictText(status: string): string {
  switch (status) {
    case "SAFE":
      return "Approved for merge";
    case "CAUTION":
      return "Proceed with caution";
    case "BLOCK":
      return "Merge blocked";
    default:
      return "Review required";
  }
}

function getFinalVerdictAction(status: string): string {
  switch (status) {
    case "SAFE":
      return "Safe to merge immediately";
    case "CAUTION":
      return "Safe to merge **after review of critical files**";
    case "BLOCK":
      return "**Fix flagged issues** before merging";
    default:
      return "Perform a full review before merging";
  }
}
