/**
 * Formats PR analysis data into a GitHub PR comment
 * Generates structured, developer-friendly comments with clear formatting
 */

import {
  PRAnalysisWithRiskScore,
  BlastRadius,
  ComplianceResult,
  MergeReadiness,
} from "@/app/types/prAnalysis";

export interface PRCommentData {
  analysis: PRAnalysisWithRiskScore;
  mergeReadiness: MergeReadiness;
  blastRadius: BlastRadius;
  compliance: ComplianceResult;
  repository?: {
    changedFiles: string[];
    totalFiles: number;
    prUrl?: string;
  };
  appUrl?: string;
}

/**
 * Generate a GitHub-ready PR comment from analysis data
 */
export function generatePRComment(data: PRCommentData): string {
  const {
    analysis,
    mergeReadiness,
    blastRadius,
    compliance,
    repository,
    appUrl,
  } = data;

  const statusEmoji = getStatusEmoji(mergeReadiness.status);
  const statusColor = getStatusColor(mergeReadiness.status);
  const complianceLevel = getComplianceLevel(compliance.riskLevel);
  const confidencePercent = Math.round(analysis.confidenceScore * 100);
  const encodedPrUrl = repository?.prUrl
    ? encodeURIComponent(repository.prUrl)
    : "";
  const fullAnalysisUrl = appUrl
    ? `${appUrl}/pr${encodedPrUrl ? `?url=${encodedPrUrl}` : ""}`
    : "";
  const EMOJI = {
    brain: "\u{1F9E0}",
    why: "\u26A1",
    blast: "\u{1F30D}",
    risk: "\u26A0\uFE0F",
    improvements: "\u{1F4A1}",
    summary: "\u{1F4CA}",
    link: "\u{1F517}",
  };

  const criticalFiles = blastRadius.layerDetails
    ? Object.entries(blastRadius.layerDetails)
        .flatMap(([layer, details]) =>
          details.files
            .filter((f) => f.isCritical)
            .map((f) => ({
              path: f.path,
              reason: f.reason,
              layer,
            }))
        )
        .slice(0, 5)
    : [];

  const comment = `## ${EMOJI.brain} MergeMind Analysis

### ${statusEmoji} **${statusColor} — ${getFinalVerdictText(
    mergeReadiness.status
  )}**

**Score:** ${mergeReadiness.score}/100  
**Confidence:** ${confidencePercent}%

---

### ${EMOJI.why} Why this matters
${formatWhyItMatters(mergeReadiness.status, analysis.issues.length || 0)}

---

### ${EMOJI.blast} Blast Radius
${formatWhatChanged(blastRadius, repository)}

---

${criticalFiles.length > 0 ? formatCriticalFilesSection(criticalFiles) + "\n" : ""}
### ${EMOJI.risk} Key Risks

---

### ${EMOJI.improvements} Suggested Improvements
${formatSuggestions(analysis.improvements)}

---

### ${EMOJI.summary} Summary
- Risk: **${analysis.riskLevel}**
- Compliance: **${complianceLevel}**
- Impact: **${mergeReadiness.score}/100**

---

${
  fullAnalysisUrl ? `\n${EMOJI.link} **View Full Analysis:** ${fullAnalysisUrl}` : ""
}

---

*Generated by MergeMind • AI Merge Readiness Engine*`;

  return comment.trim();
}

function getStatusEmoji(status: string): string {
  switch (status) {
    case "SAFE":
      return "\u{1F7E2}";
    case "CAUTION":
      return "\u{1F7E1}";
    case "BLOCK":
      return "\u{1F534}";
    default:
      return "\u26AA";
  }
}

function getStatusColor(status: string): string {
  switch (status) {
    case "SAFE":
      return "SAFE";
    case "CAUTION":
      return "CAUTION";
    case "BLOCK":
      return "BLOCK";
    default:
      return "UNKNOWN";
  }
}

function formatWhyItMatters(status: string, issueCount: number): string {
  const lines: string[] = [];

  switch (status) {
    case "SAFE":
      lines.push("- Low risk detected in code changes");
      lines.push("- No major concerns identified");
      lines.push("- Safe to merge immediately");
      break;
    case "CAUTION":
      lines.push("- Moderate risk detected in code changes");
      lines.push("- Some important logic areas affected");
      lines.push("- Review recommended before merging");
      break;
    case "BLOCK":
      lines.push("- High risk detected in code changes");
      lines.push("- Critical issues must be addressed");
      lines.push("- Address concerns before merging");
      break;
  }

  if (issueCount > 0) {
    lines.push(`- ${issueCount} issue${issueCount !== 1 ? "s" : ""} found`);
  }

  return lines.join("\n");
}

function getComplianceLevel(riskLevel: string): string {
  switch (riskLevel) {
    case "LOW":
      return "LOW";
    case "MEDIUM":
      return "MEDIUM";
    case "HIGH":
      return "HIGH";
    default:
      return "UNKNOWN";
  }
}

function formatWhatChanged(
  blastRadius: BlastRadius,
  repository?: { changedFiles: string[]; totalFiles: number; prUrl?: string }
): string {
  const lines: string[] = [];

  if (blastRadius.affectedLayers.length > 0) {
    lines.push(
      `- ${blastRadius.affectedLayers.length} architectural layer${
        blastRadius.affectedLayers.length !== 1 ? "s" : ""
      } affected`
    );
    lines.push(`- Layers: ${blastRadius.affectedLayers.join(", ")}`);
  }

  if (repository) {
    lines.push(
      `- ${repository.changedFiles.length} file${
        repository.changedFiles.length !== 1 ? "s" : ""
      } changed`
    );
  }

  if (blastRadius.impactScore) {
    lines.push(`- Impact score: ${blastRadius.impactScore}%`);
  }

  return lines.length > 0 ? lines.join("\n") : "- Analysis data unavailable";
}

function formatCriticalFilesSection(
  criticalFiles: Array<{ path: string; reason: string; layer: string }>
): string {
  if (criticalFiles.length === 0) return "";

  const fileList = criticalFiles
    .map((f) => `- **${f.path}** \u2192 ${f.reason}`)
    .join("\n");

  return `### \u{1F525} Critical Files (High Attention)\n${fileList}\n\n`;
}

function formatKeyRisks(issues: PRAnalysisWithRiskScore["issues"]): string {
  if (!issues || issues.length === 0) {
    return "- No major risks detected";
  }

  return issues
    .slice(0, 5)
    .map((issue) => `- ${issue.description || "Potential issue detected"}`)
    .join("\n");
}

function formatSuggestions(improvements: string[]): string {
  if (improvements.length === 0) {
    return "- Code looks good\n- Keep maintaining the current standards";
  }

  return improvements
    .slice(0, 5)
    .map((s) => `- ${s}`)
    .join("\n");
}

function getFinalVerdictText(status: string): string {
  switch (status) {
    case "SAFE":
      return "Approved for merge";
    case "CAUTION":
      return "Proceed with caution";
    case "BLOCK":
      return "Merge blocked";
    default:
      return "Review required";
  }
}

